[package]
name = "fakecargo"
version = "0.2.51"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "fake cargo for single rust files"
repository = "https://github.com/sigmaSd/fakecargo"
license = "MIT"

[dependencies]
